language: node_js
node_js:
  - "0.10"
install:
  - "npm install -g casperjs"
before_script:
  - "node test/server.js &"
  - "sleep 3"
  - "ps -fA | grep node"
script:
  - "npm test"
notifications:
  email: alessandro.nadalin@gmail.com